### ISSUE TITLE
colorma

### ISSUE THREAD

**Issue by RayBB** [MaliciouSSymbol/Ob3vil1on#3]
When I try to run it I get the following error:

```
Traceback (most recent call last):
  File "Obevilion.py", line 10, in <module>
    from core import Check, Control
  File "/Users/rr/Downloads/Ob3vil1on-master/core/Check.py", line 14, in <module>
    from writer import OpenFile
  File "/Users/rr/Downloads/Ob3vil1on-master/core/writer.py", line 14, in <module>
    import colorama
ImportError: No module named colorama
```

**Comment by iossefy** [comment]
Type this into your command line

pip install colorama
